<?php
/**
 * Created by PhpStorm.
 * User: wy
 * Date: 2019/2/25
 * Time: 15:31
 */

namespace app\models;

use yii\db\ActiveRecord;//自定义模型类一定要继承这个类

class Test extends ActiveRecord
{
    //指定该类对应的mysql数据表名
    public static function tableName()
    {
//        return parent::tableName(); // TODO: Change the autogenerated stub
//        return "imooc_test"; //由于db.php配置脚本中已经指定了表前缀,所以要写成如下形式
        return "{{%test}}";

    }

    ///验证器
    public function rules()
    {
//        return parent::rules(); // TODO: Change the autogenerated stub
        return [
//            ['id' , 'integer'],//表示限制id是整型
            ['id' , 'integer' , 'message'=> '傻了吧 , id需要整型数据'],//表示限制id是整型,自定义错误提示语
//            ['title' ,'string' ,'length'=>[0,5] ] // 表示限制title需要时字符串类型  , 且长度为0 到 5之间
            ['title' ,'string' ,'length'=>[2,55] , 'tooLong'=>'笨蛋,字符串要限制在2到5个字符以内哦' , 'tooShort'=>'不开窍,至少有字符啊得' ] // 表示限制title需要时字符串类型  , 且长度为0 到 5之间
        ];
    }

}